// Code generated by Fern. DO NOT EDIT.

package fleet

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
	big "math/big"
)

var (
	getDevicesRequestFieldID = big.NewInt(1 << 0)
)

type GetDevicesRequest struct {
	// The machine id: 16 lower-case hex digits
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDevicesRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDevicesRequest) SetID(id string) {
	g.ID = id
	g.require(getDevicesRequestFieldID)
}

var (
	historyDevicesRequestFieldID    = big.NewInt(1 << 0)
	historyDevicesRequestFieldSince = big.NewInt(1 << 1)
	historyDevicesRequestFieldLimit = big.NewInt(1 << 2)
)

type HistoryDevicesRequest struct {
	// The machine id: 16 lower-case hex digits
	ID string `json:"-" url:"-"`
	// Only reports received at or after this, Unix milliseconds; 0: all that are kept
	Since *int64 `json:"-" url:"since,omitempty"`
	// At most this many, newest first
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HistoryDevicesRequest) require(field *big.Int) {
	next := new(big.Int)
	if h.explicitFields != nil {
		next.Set(h.explicitFields)
	}
	next.Or(next, field)
	h.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryDevicesRequest) SetID(id string) {
	h.ID = id
	h.require(historyDevicesRequestFieldID)
}

// SetSince sets the Since field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryDevicesRequest) SetSince(since *int64) {
	h.Since = since
	h.require(historyDevicesRequestFieldSince)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HistoryDevicesRequest) SetLimit(limit *int) {
	h.Limit = limit
	h.require(historyDevicesRequestFieldLimit)
}

var (
	reportDevicesRequestFieldID = big.NewInt(1 << 0)
)

type ReportDevicesRequest struct {
	// The machine id; must be the report's id
	ID   string        `json:"-" url:"-"`
	Body *DeviceReport `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *ReportDevicesRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReportDevicesRequest) SetID(id string) {
	r.ID = id
	r.require(reportDevicesRequestFieldID)
}

func (r *ReportDevicesRequest) UnmarshalJSON(data []byte) error {
	body := new(DeviceReport)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	r.Body = body
	return nil
}

func (r *ReportDevicesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Body)
}

var (
	deviceBatteryFieldCount      = big.NewInt(1 << 0)
	deviceBatteryFieldHealth     = big.NewInt(1 << 1)
	deviceBatteryFieldPercent    = big.NewInt(1 << 2)
	deviceBatteryFieldRemainingS = big.NewInt(1 << 3)
	deviceBatteryFieldState      = big.NewInt(1 << 4)
	deviceBatteryFieldStatus     = big.NewInt(1 << 5)
	deviceBatteryFieldWhy        = big.NewInt(1 << 6)
)

type DeviceBattery struct {
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Full capacity as a percent of design capacity; absent when the OS does not say.
	Health *float64 `json:"health,omitempty" url:"health,omitempty"`
	// Charge, as the OS shows it.
	Percent *float64 `json:"percent,omitempty" url:"percent,omitempty"`
	// The OS's estimate to empty or to full, seconds; absent when it has none.
	RemainingS *int64 `json:"remaining_s,omitempty" url:"remaining_s,omitempty"`
	// idle: on external power, neither charging nor full (a charge limit).
	State  *DeviceBatteryState `json:"state,omitempty" url:"state,omitempty"`
	Status DeviceBatteryStatus `json:"status" url:"status"`
	Why    *string             `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceBattery) GetCount() *int {
	if d == nil {
		return nil
	}
	return d.Count
}

func (d *DeviceBattery) GetHealth() *float64 {
	if d == nil {
		return nil
	}
	return d.Health
}

func (d *DeviceBattery) GetPercent() *float64 {
	if d == nil {
		return nil
	}
	return d.Percent
}

func (d *DeviceBattery) GetRemainingS() *int64 {
	if d == nil {
		return nil
	}
	return d.RemainingS
}

func (d *DeviceBattery) GetState() *DeviceBatteryState {
	if d == nil {
		return nil
	}
	return d.State
}

func (d *DeviceBattery) GetStatus() DeviceBatteryStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceBattery) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceBattery) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceBattery) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetCount(count *int) {
	d.Count = count
	d.require(deviceBatteryFieldCount)
}

// SetHealth sets the Health field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetHealth(health *float64) {
	d.Health = health
	d.require(deviceBatteryFieldHealth)
}

// SetPercent sets the Percent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetPercent(percent *float64) {
	d.Percent = percent
	d.require(deviceBatteryFieldPercent)
}

// SetRemainingS sets the RemainingS field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetRemainingS(remainingS *int64) {
	d.RemainingS = remainingS
	d.require(deviceBatteryFieldRemainingS)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetState(state *DeviceBatteryState) {
	d.State = state
	d.require(deviceBatteryFieldState)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetStatus(status DeviceBatteryStatus) {
	d.Status = status
	d.require(deviceBatteryFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceBattery) SetWhy(why *string) {
	d.Why = why
	d.require(deviceBatteryFieldWhy)
}

func (d *DeviceBattery) UnmarshalJSON(data []byte) error {
	type embed DeviceBattery
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceBattery(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceBattery) MarshalJSON() ([]byte, error) {
	type embed DeviceBattery
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceBattery) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// idle: on external power, neither charging nor full (a charge limit).
type DeviceBatteryState string

const (
	DeviceBatteryStateCharging    DeviceBatteryState = "charging"
	DeviceBatteryStateDischarging DeviceBatteryState = "discharging"
	DeviceBatteryStateFull        DeviceBatteryState = "full"
	DeviceBatteryStateIdle        DeviceBatteryState = "idle"
)

func NewDeviceBatteryStateFromString(s string) (DeviceBatteryState, error) {
	switch s {
	case "charging":
		return DeviceBatteryStateCharging, nil
	case "discharging":
		return DeviceBatteryStateDischarging, nil
	case "full":
		return DeviceBatteryStateFull, nil
	case "idle":
		return DeviceBatteryStateIdle, nil
	}
	var t DeviceBatteryState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceBatteryState) Ptr() *DeviceBatteryState {
	return &d
}

type DeviceBatteryStatus string

const (
	DeviceBatteryStatusOk      DeviceBatteryStatus = "ok"
	DeviceBatteryStatusNone    DeviceBatteryStatus = "none"
	DeviceBatteryStatusUnknown DeviceBatteryStatus = "unknown"
)

func NewDeviceBatteryStatusFromString(s string) (DeviceBatteryStatus, error) {
	switch s {
	case "ok":
		return DeviceBatteryStatusOk, nil
	case "none":
		return DeviceBatteryStatusNone, nil
	case "unknown":
		return DeviceBatteryStatusUnknown, nil
	}
	var t DeviceBatteryStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceBatteryStatus) Ptr() *DeviceBatteryStatus {
	return &d
}

var (
	deviceClaimFieldCaller = big.NewInt(1 << 0)
	deviceClaimFieldID     = big.NewInt(1 << 1)
	deviceClaimFieldJob    = big.NewInt(1 << 2)
	deviceClaimFieldSince  = big.NewInt(1 << 3)
	deviceClaimFieldUntil  = big.NewInt(1 << 4)
)

type DeviceClaim struct {
	// Who holds it: an agent, a session or a tool. Never a person's user name or address, so no @.
	Caller string `json:"caller" url:"caller"`
	// The claim's id on the machine.
	ID string `json:"id" url:"id"`
	// What it is doing.
	Job string `json:"job" url:"job"`
	// When it was taken, Unix milliseconds, by the machine's clock.
	Since int64 `json:"since" url:"since"`
	// When it lapses unless renewed, Unix milliseconds; absent when it does not lapse.
	Until *int64 `json:"until,omitempty" url:"until,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceClaim) GetCaller() string {
	if d == nil {
		return ""
	}
	return d.Caller
}

func (d *DeviceClaim) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeviceClaim) GetJob() string {
	if d == nil {
		return ""
	}
	return d.Job
}

func (d *DeviceClaim) GetSince() int64 {
	if d == nil {
		return 0
	}
	return d.Since
}

func (d *DeviceClaim) GetUntil() *int64 {
	if d == nil {
		return nil
	}
	return d.Until
}

func (d *DeviceClaim) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceClaim) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetCaller sets the Caller field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaim) SetCaller(caller string) {
	d.Caller = caller
	d.require(deviceClaimFieldCaller)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaim) SetID(id string) {
	d.ID = id
	d.require(deviceClaimFieldID)
}

// SetJob sets the Job field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaim) SetJob(job string) {
	d.Job = job
	d.require(deviceClaimFieldJob)
}

// SetSince sets the Since field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaim) SetSince(since int64) {
	d.Since = since
	d.require(deviceClaimFieldSince)
}

// SetUntil sets the Until field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaim) SetUntil(until *int64) {
	d.Until = until
	d.require(deviceClaimFieldUntil)
}

func (d *DeviceClaim) UnmarshalJSON(data []byte) error {
	type embed DeviceClaim
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceClaim(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceClaim) MarshalJSON() ([]byte, error) {
	type embed DeviceClaim
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceClaim) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceClaimsFieldHeld   = big.NewInt(1 << 0)
	deviceClaimsFieldSlots  = big.NewInt(1 << 1)
	deviceClaimsFieldStatus = big.NewInt(1 << 2)
	deviceClaimsFieldWhy    = big.NewInt(1 << 3)
)

type DeviceClaims struct {
	// The claims held now; empty or absent when the machine is free.
	Held []*DeviceClaim `json:"held,omitempty" url:"held,omitempty"`
	// How many jobs it takes at once.
	Slots *int `json:"slots,omitempty" url:"slots,omitempty"`
	// none: this machine takes no claims.
	Status DeviceClaimsStatus `json:"status" url:"status"`
	Why    *string            `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceClaims) GetHeld() []*DeviceClaim {
	if d == nil {
		return nil
	}
	return d.Held
}

func (d *DeviceClaims) GetSlots() *int {
	if d == nil {
		return nil
	}
	return d.Slots
}

func (d *DeviceClaims) GetStatus() DeviceClaimsStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceClaims) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceClaims) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceClaims) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetHeld sets the Held field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaims) SetHeld(held []*DeviceClaim) {
	d.Held = held
	d.require(deviceClaimsFieldHeld)
}

// SetSlots sets the Slots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaims) SetSlots(slots *int) {
	d.Slots = slots
	d.require(deviceClaimsFieldSlots)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaims) SetStatus(status DeviceClaimsStatus) {
	d.Status = status
	d.require(deviceClaimsFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceClaims) SetWhy(why *string) {
	d.Why = why
	d.require(deviceClaimsFieldWhy)
}

func (d *DeviceClaims) UnmarshalJSON(data []byte) error {
	type embed DeviceClaims
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceClaims(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceClaims) MarshalJSON() ([]byte, error) {
	type embed DeviceClaims
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceClaims) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// none: this machine takes no claims.
type DeviceClaimsStatus string

const (
	DeviceClaimsStatusOk      DeviceClaimsStatus = "ok"
	DeviceClaimsStatusNone    DeviceClaimsStatus = "none"
	DeviceClaimsStatusUnknown DeviceClaimsStatus = "unknown"
)

func NewDeviceClaimsStatusFromString(s string) (DeviceClaimsStatus, error) {
	switch s {
	case "ok":
		return DeviceClaimsStatusOk, nil
	case "none":
		return DeviceClaimsStatusNone, nil
	case "unknown":
		return DeviceClaimsStatusUnknown, nil
	}
	var t DeviceClaimsStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceClaimsStatus) Ptr() *DeviceClaimsStatus {
	return &d
}

var (
	deviceConditionFieldCode  = big.NewInt(1 << 0)
	deviceConditionFieldSince = big.NewInt(1 << 1)
	deviceConditionFieldWhy   = big.NewInt(1 << 2)
)

type DeviceCondition struct {
	Code DeviceConditionCode `json:"code" url:"code"`
	// When it began to hold, as far as the Worker knows: when the report that shows it was received, or for quiet when the report became late. Unix milliseconds.
	Since int64 `json:"since" url:"since"`
	// One sentence, with the numbers.
	Why string `json:"why" url:"why"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceCondition) GetCode() DeviceConditionCode {
	if d == nil {
		return ""
	}
	return d.Code
}

func (d *DeviceCondition) GetSince() int64 {
	if d == nil {
		return 0
	}
	return d.Since
}

func (d *DeviceCondition) GetWhy() string {
	if d == nil {
		return ""
	}
	return d.Why
}

func (d *DeviceCondition) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceCondition) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCondition) SetCode(code DeviceConditionCode) {
	d.Code = code
	d.require(deviceConditionFieldCode)
}

// SetSince sets the Since field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCondition) SetSince(since int64) {
	d.Since = since
	d.require(deviceConditionFieldSince)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCondition) SetWhy(why string) {
	d.Why = why
	d.require(deviceConditionFieldWhy)
}

func (d *DeviceCondition) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceCondition
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceCondition(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceCondition) MarshalJSON() ([]byte, error) {
	type embed DeviceCondition
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceCondition) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceConditionCode string

const (
	DeviceConditionCodeStopped         DeviceConditionCode = "stopped"
	DeviceConditionCodeQuiet           DeviceConditionCode = "quiet"
	DeviceConditionCodeUnminded        DeviceConditionCode = "unminded"
	DeviceConditionCodeClosedOnBattery DeviceConditionCode = "closed-on-battery"
	DeviceConditionCodeBatteryLow      DeviceConditionCode = "battery-low"
	DeviceConditionCodeRigUnready      DeviceConditionCode = "rig-unready"
)

func NewDeviceConditionCodeFromString(s string) (DeviceConditionCode, error) {
	switch s {
	case "stopped":
		return DeviceConditionCodeStopped, nil
	case "quiet":
		return DeviceConditionCodeQuiet, nil
	case "unminded":
		return DeviceConditionCodeUnminded, nil
	case "closed-on-battery":
		return DeviceConditionCodeClosedOnBattery, nil
	case "battery-low":
		return DeviceConditionCodeBatteryLow, nil
	case "rig-unready":
		return DeviceConditionCodeRigUnready, nil
	}
	var t DeviceConditionCode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceConditionCode) Ptr() *DeviceConditionCode {
	return &d
}

var (
	deviceCPUFieldCount  = big.NewInt(1 << 0)
	deviceCPUFieldLoad1  = big.NewInt(1 << 1)
	deviceCPUFieldStatus = big.NewInt(1 << 2)
	deviceCPUFieldWhy    = big.NewInt(1 << 3)
)

type DeviceCPU struct {
	// Logical processors.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// The one-minute load average; absent on Windows, which has none.
	Load1  *float64        `json:"load1,omitempty" url:"load1,omitempty"`
	Status DeviceCPUStatus `json:"status" url:"status"`
	Why    *string         `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceCPU) GetCount() *int {
	if d == nil {
		return nil
	}
	return d.Count
}

func (d *DeviceCPU) GetLoad1() *float64 {
	if d == nil {
		return nil
	}
	return d.Load1
}

func (d *DeviceCPU) GetStatus() DeviceCPUStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceCPU) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceCPU) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceCPU) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCPU) SetCount(count *int) {
	d.Count = count
	d.require(deviceCPUFieldCount)
}

// SetLoad1 sets the Load1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCPU) SetLoad1(load1 *float64) {
	d.Load1 = load1
	d.require(deviceCPUFieldLoad1)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCPU) SetStatus(status DeviceCPUStatus) {
	d.Status = status
	d.require(deviceCPUFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceCPU) SetWhy(why *string) {
	d.Why = why
	d.require(deviceCPUFieldWhy)
}

func (d *DeviceCPU) UnmarshalJSON(data []byte) error {
	type embed DeviceCPU
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceCPU(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceCPU) MarshalJSON() ([]byte, error) {
	type embed DeviceCPU
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceCPU) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceCPUStatus string

const (
	DeviceCPUStatusOk      DeviceCPUStatus = "ok"
	DeviceCPUStatusUnknown DeviceCPUStatus = "unknown"
)

func NewDeviceCPUStatusFromString(s string) (DeviceCPUStatus, error) {
	switch s {
	case "ok":
		return DeviceCPUStatusOk, nil
	case "unknown":
		return DeviceCPUStatusUnknown, nil
	}
	var t DeviceCPUStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceCPUStatus) Ptr() *DeviceCPUStatus {
	return &d
}

var (
	deviceDiskFieldFree   = big.NewInt(1 << 0)
	deviceDiskFieldFs     = big.NewInt(1 << 1)
	deviceDiskFieldPath   = big.NewInt(1 << 2)
	deviceDiskFieldRoles  = big.NewInt(1 << 3)
	deviceDiskFieldStatus = big.NewInt(1 << 4)
	deviceDiskFieldTotal  = big.NewInt(1 << 5)
	deviceDiskFieldWhy    = big.NewInt(1 << 6)
)

type DeviceDisk struct {
	// What this user can still write.
	Free *int64 `json:"free,omitempty" url:"free,omitempty"`
	// apfs, ext4, NTFS.
	Fs *string `json:"fs,omitempty" url:"fs,omitempty"`
	// Where it is mounted, the home directory written as ~.
	Path string `json:"path" url:"path"`
	// system: the OS's volume. data: where the tool keeps its work.
	Roles  []DeviceDiskRolesItem `json:"roles" url:"roles"`
	Status DeviceDiskStatus      `json:"status" url:"status"`
	Total  *int64                `json:"total,omitempty" url:"total,omitempty"`
	Why    *string               `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceDisk) GetFree() *int64 {
	if d == nil {
		return nil
	}
	return d.Free
}

func (d *DeviceDisk) GetFs() *string {
	if d == nil {
		return nil
	}
	return d.Fs
}

func (d *DeviceDisk) GetPath() string {
	if d == nil {
		return ""
	}
	return d.Path
}

func (d *DeviceDisk) GetRoles() []DeviceDiskRolesItem {
	if d == nil {
		return nil
	}
	return d.Roles
}

func (d *DeviceDisk) GetStatus() DeviceDiskStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceDisk) GetTotal() *int64 {
	if d == nil {
		return nil
	}
	return d.Total
}

func (d *DeviceDisk) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceDisk) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceDisk) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetFree sets the Free field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetFree(free *int64) {
	d.Free = free
	d.require(deviceDiskFieldFree)
}

// SetFs sets the Fs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetFs(fs *string) {
	d.Fs = fs
	d.require(deviceDiskFieldFs)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetPath(path string) {
	d.Path = path
	d.require(deviceDiskFieldPath)
}

// SetRoles sets the Roles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetRoles(roles []DeviceDiskRolesItem) {
	d.Roles = roles
	d.require(deviceDiskFieldRoles)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetStatus(status DeviceDiskStatus) {
	d.Status = status
	d.require(deviceDiskFieldStatus)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetTotal(total *int64) {
	d.Total = total
	d.require(deviceDiskFieldTotal)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceDisk) SetWhy(why *string) {
	d.Why = why
	d.require(deviceDiskFieldWhy)
}

func (d *DeviceDisk) UnmarshalJSON(data []byte) error {
	type embed DeviceDisk
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceDisk(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceDisk) MarshalJSON() ([]byte, error) {
	type embed DeviceDisk
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceDisk) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceDiskRolesItem string

const (
	DeviceDiskRolesItemSystem DeviceDiskRolesItem = "system"
	DeviceDiskRolesItemData   DeviceDiskRolesItem = "data"
)

func NewDeviceDiskRolesItemFromString(s string) (DeviceDiskRolesItem, error) {
	switch s {
	case "system":
		return DeviceDiskRolesItemSystem, nil
	case "data":
		return DeviceDiskRolesItemData, nil
	}
	var t DeviceDiskRolesItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceDiskRolesItem) Ptr() *DeviceDiskRolesItem {
	return &d
}

type DeviceDiskStatus string

const (
	DeviceDiskStatusOk      DeviceDiskStatus = "ok"
	DeviceDiskStatusUnknown DeviceDiskStatus = "unknown"
)

func NewDeviceDiskStatusFromString(s string) (DeviceDiskStatus, error) {
	switch s {
	case "ok":
		return DeviceDiskStatusOk, nil
	case "unknown":
		return DeviceDiskStatusUnknown, nil
	}
	var t DeviceDiskStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceDiskStatus) Ptr() *DeviceDiskStatus {
	return &d
}

var (
	deviceHistoryFieldID      = big.NewInt(1 << 0)
	deviceHistoryFieldReports = big.NewInt(1 << 1)
)

type DeviceHistory struct {
	ID      string          `json:"id" url:"id"`
	Reports []*DeviceStored `json:"reports" url:"reports"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceHistory) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeviceHistory) GetReports() []*DeviceStored {
	if d == nil {
		return nil
	}
	return d.Reports
}

func (d *DeviceHistory) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceHistory) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHistory) SetID(id string) {
	d.ID = id
	d.require(deviceHistoryFieldID)
}

// SetReports sets the Reports field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHistory) SetReports(reports []*DeviceStored) {
	d.Reports = reports
	d.require(deviceHistoryFieldReports)
}

func (d *DeviceHistory) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceHistory
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceHistory(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceHistory) MarshalJSON() ([]byte, error) {
	type embed DeviceHistory
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceHistory) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceHostFieldArch      = big.NewInt(1 << 0)
	deviceHostFieldBoot      = big.NewInt(1 << 1)
	deviceHostFieldGuest     = big.NewInt(1 << 2)
	deviceHostFieldModel     = big.NewInt(1 << 3)
	deviceHostFieldName      = big.NewInt(1 << 4)
	deviceHostFieldOs        = big.NewInt(1 << 5)
	deviceHostFieldOsName    = big.NewInt(1 << 6)
	deviceHostFieldOsVersion = big.NewInt(1 << 7)
)

type DeviceHost struct {
	// GOARCH: arm64, amd64.
	Arch string `json:"arch" url:"arch"`
	// When it booted, Unix milliseconds.
	Boot *int64 `json:"boot,omitempty" url:"boot,omitempty"`
	// True in a virtual machine; absent when that cannot be told.
	Guest *bool `json:"guest,omitempty" url:"guest,omitempty"`
	// The hardware model, Mac14,10. Never a serial number.
	Model *string `json:"model,omitempty" url:"model,omitempty"`
	// The hostname's first label.
	Name string `json:"name" url:"name"`
	// GOOS.
	Os DeviceHostOs `json:"os" url:"os"`
	// macOS, Ubuntu, Windows 11 Pro.
	OsName    *string `json:"os_name,omitempty" url:"os_name,omitempty"`
	OsVersion *string `json:"os_version,omitempty" url:"os_version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceHost) GetArch() string {
	if d == nil {
		return ""
	}
	return d.Arch
}

func (d *DeviceHost) GetBoot() *int64 {
	if d == nil {
		return nil
	}
	return d.Boot
}

func (d *DeviceHost) GetGuest() *bool {
	if d == nil {
		return nil
	}
	return d.Guest
}

func (d *DeviceHost) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeviceHost) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeviceHost) GetOs() DeviceHostOs {
	if d == nil {
		return ""
	}
	return d.Os
}

func (d *DeviceHost) GetOsName() *string {
	if d == nil {
		return nil
	}
	return d.OsName
}

func (d *DeviceHost) GetOsVersion() *string {
	if d == nil {
		return nil
	}
	return d.OsVersion
}

func (d *DeviceHost) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceHost) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetArch sets the Arch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetArch(arch string) {
	d.Arch = arch
	d.require(deviceHostFieldArch)
}

// SetBoot sets the Boot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetBoot(boot *int64) {
	d.Boot = boot
	d.require(deviceHostFieldBoot)
}

// SetGuest sets the Guest field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetGuest(guest *bool) {
	d.Guest = guest
	d.require(deviceHostFieldGuest)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetModel(model *string) {
	d.Model = model
	d.require(deviceHostFieldModel)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetName(name string) {
	d.Name = name
	d.require(deviceHostFieldName)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetOs(os DeviceHostOs) {
	d.Os = os
	d.require(deviceHostFieldOs)
}

// SetOsName sets the OsName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetOsName(osName *string) {
	d.OsName = osName
	d.require(deviceHostFieldOsName)
}

// SetOsVersion sets the OsVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceHost) SetOsVersion(osVersion *string) {
	d.OsVersion = osVersion
	d.require(deviceHostFieldOsVersion)
}

func (d *DeviceHost) UnmarshalJSON(data []byte) error {
	type embed DeviceHost
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceHost(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceHost) MarshalJSON() ([]byte, error) {
	type embed DeviceHost
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceHost) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// GOOS.
type DeviceHostOs string

const (
	DeviceHostOsDarwin  DeviceHostOs = "darwin"
	DeviceHostOsLinux   DeviceHostOs = "linux"
	DeviceHostOsWindows DeviceHostOs = "windows"
)

func NewDeviceHostOsFromString(s string) (DeviceHostOs, error) {
	switch s {
	case "darwin":
		return DeviceHostOsDarwin, nil
	case "linux":
		return DeviceHostOsLinux, nil
	case "windows":
		return DeviceHostOsWindows, nil
	}
	var t DeviceHostOs
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceHostOs) Ptr() *DeviceHostOs {
	return &d
}

var (
	deviceKeeperFieldIdle    = big.NewInt(1 << 0)
	deviceKeeperFieldLid     = big.NewInt(1 << 1)
	deviceKeeperFieldRunning = big.NewInt(1 << 2)
	deviceKeeperFieldStatus  = big.NewInt(1 << 3)
	deviceKeeperFieldWhy     = big.NewInt(1 << 4)
)

type DeviceKeeper struct {
	// It is holding idle sleep off.
	Idle *bool `json:"idle,omitempty" url:"idle,omitempty"`
	// It has set closing the lid to do nothing.
	Lid     *bool `json:"lid,omitempty" url:"lid,omitempty"`
	Running *bool `json:"running,omitempty" url:"running,omitempty"`
	// none: the tool has no keep-awake for this OS.
	Status DeviceKeeperStatus `json:"status" url:"status"`
	Why    *string            `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceKeeper) GetIdle() *bool {
	if d == nil {
		return nil
	}
	return d.Idle
}

func (d *DeviceKeeper) GetLid() *bool {
	if d == nil {
		return nil
	}
	return d.Lid
}

func (d *DeviceKeeper) GetRunning() *bool {
	if d == nil {
		return nil
	}
	return d.Running
}

func (d *DeviceKeeper) GetStatus() DeviceKeeperStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceKeeper) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceKeeper) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceKeeper) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetIdle sets the Idle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceKeeper) SetIdle(idle *bool) {
	d.Idle = idle
	d.require(deviceKeeperFieldIdle)
}

// SetLid sets the Lid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceKeeper) SetLid(lid *bool) {
	d.Lid = lid
	d.require(deviceKeeperFieldLid)
}

// SetRunning sets the Running field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceKeeper) SetRunning(running *bool) {
	d.Running = running
	d.require(deviceKeeperFieldRunning)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceKeeper) SetStatus(status DeviceKeeperStatus) {
	d.Status = status
	d.require(deviceKeeperFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceKeeper) SetWhy(why *string) {
	d.Why = why
	d.require(deviceKeeperFieldWhy)
}

func (d *DeviceKeeper) UnmarshalJSON(data []byte) error {
	type embed DeviceKeeper
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceKeeper(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceKeeper) MarshalJSON() ([]byte, error) {
	type embed DeviceKeeper
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceKeeper) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// none: the tool has no keep-awake for this OS.
type DeviceKeeperStatus string

const (
	DeviceKeeperStatusOk      DeviceKeeperStatus = "ok"
	DeviceKeeperStatusNone    DeviceKeeperStatus = "none"
	DeviceKeeperStatusUnknown DeviceKeeperStatus = "unknown"
)

func NewDeviceKeeperStatusFromString(s string) (DeviceKeeperStatus, error) {
	switch s {
	case "ok":
		return DeviceKeeperStatusOk, nil
	case "none":
		return DeviceKeeperStatusNone, nil
	case "unknown":
		return DeviceKeeperStatusUnknown, nil
	}
	var t DeviceKeeperStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceKeeperStatus) Ptr() *DeviceKeeperStatus {
	return &d
}

var (
	deviceLidFieldClosed = big.NewInt(1 << 0)
	deviceLidFieldStatus = big.NewInt(1 << 1)
	deviceLidFieldWhy    = big.NewInt(1 << 2)
)

type DeviceLid struct {
	Closed *bool           `json:"closed,omitempty" url:"closed,omitempty"`
	Status DeviceLidStatus `json:"status" url:"status"`
	Why    *string         `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceLid) GetClosed() *bool {
	if d == nil {
		return nil
	}
	return d.Closed
}

func (d *DeviceLid) GetStatus() DeviceLidStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceLid) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceLid) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceLid) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetClosed sets the Closed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceLid) SetClosed(closed *bool) {
	d.Closed = closed
	d.require(deviceLidFieldClosed)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceLid) SetStatus(status DeviceLidStatus) {
	d.Status = status
	d.require(deviceLidFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceLid) SetWhy(why *string) {
	d.Why = why
	d.require(deviceLidFieldWhy)
}

func (d *DeviceLid) UnmarshalJSON(data []byte) error {
	type embed DeviceLid
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceLid(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceLid) MarshalJSON() ([]byte, error) {
	type embed DeviceLid
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceLid) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceLidStatus string

const (
	DeviceLidStatusOk      DeviceLidStatus = "ok"
	DeviceLidStatusNone    DeviceLidStatus = "none"
	DeviceLidStatusUnknown DeviceLidStatus = "unknown"
)

func NewDeviceLidStatusFromString(s string) (DeviceLidStatus, error) {
	switch s {
	case "ok":
		return DeviceLidStatusOk, nil
	case "none":
		return DeviceLidStatusNone, nil
	case "unknown":
		return DeviceLidStatusUnknown, nil
	}
	var t DeviceLidStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceLidStatus) Ptr() *DeviceLidStatus {
	return &d
}

var (
	deviceListFieldDevices = big.NewInt(1 << 0)
	deviceListFieldNow     = big.NewInt(1 << 1)
)

type DeviceList struct {
	// By id.
	Devices []*DeviceView `json:"devices" url:"devices"`
	// The Worker's clock, Unix milliseconds: what due and quiet are judged against.
	Now int64 `json:"now" url:"now"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceList) GetDevices() []*DeviceView {
	if d == nil {
		return nil
	}
	return d.Devices
}

func (d *DeviceList) GetNow() int64 {
	if d == nil {
		return 0
	}
	return d.Now
}

func (d *DeviceList) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceList) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetDevices sets the Devices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceList) SetDevices(devices []*DeviceView) {
	d.Devices = devices
	d.require(deviceListFieldDevices)
}

// SetNow sets the Now field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceList) SetNow(now int64) {
	d.Now = now
	d.require(deviceListFieldNow)
}

func (d *DeviceList) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceList
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceList(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceList) MarshalJSON() ([]byte, error) {
	type embed DeviceList
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceList) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceMemoryFieldAvailable = big.NewInt(1 << 0)
	deviceMemoryFieldStatus    = big.NewInt(1 << 1)
	deviceMemoryFieldTotal     = big.NewInt(1 << 2)
	deviceMemoryFieldWhy       = big.NewInt(1 << 3)
)

type DeviceMemory struct {
	// What a new program could have without swapping.
	Available *int64             `json:"available,omitempty" url:"available,omitempty"`
	Status    DeviceMemoryStatus `json:"status" url:"status"`
	Total     *int64             `json:"total,omitempty" url:"total,omitempty"`
	Why       *string            `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceMemory) GetAvailable() *int64 {
	if d == nil {
		return nil
	}
	return d.Available
}

func (d *DeviceMemory) GetStatus() DeviceMemoryStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceMemory) GetTotal() *int64 {
	if d == nil {
		return nil
	}
	return d.Total
}

func (d *DeviceMemory) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceMemory) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceMemory) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetAvailable sets the Available field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceMemory) SetAvailable(available *int64) {
	d.Available = available
	d.require(deviceMemoryFieldAvailable)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceMemory) SetStatus(status DeviceMemoryStatus) {
	d.Status = status
	d.require(deviceMemoryFieldStatus)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceMemory) SetTotal(total *int64) {
	d.Total = total
	d.require(deviceMemoryFieldTotal)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceMemory) SetWhy(why *string) {
	d.Why = why
	d.require(deviceMemoryFieldWhy)
}

func (d *DeviceMemory) UnmarshalJSON(data []byte) error {
	type embed DeviceMemory
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceMemory(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceMemory) MarshalJSON() ([]byte, error) {
	type embed DeviceMemory
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceMemory) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DeviceMemoryStatus string

const (
	DeviceMemoryStatusOk      DeviceMemoryStatus = "ok"
	DeviceMemoryStatusUnknown DeviceMemoryStatus = "unknown"
)

func NewDeviceMemoryStatusFromString(s string) (DeviceMemoryStatus, error) {
	switch s {
	case "ok":
		return DeviceMemoryStatusOk, nil
	case "unknown":
		return DeviceMemoryStatusUnknown, nil
	}
	var t DeviceMemoryStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceMemoryStatus) Ptr() *DeviceMemoryStatus {
	return &d
}

var (
	devicePostedFieldConditions = big.NewInt(1 << 0)
	devicePostedFieldDuplicate  = big.NewInt(1 << 1)
	devicePostedFieldID         = big.NewInt(1 << 2)
	devicePostedFieldReceived   = big.NewInt(1 << 3)
)

type DevicePosted struct {
	Conditions []*DeviceCondition `json:"conditions" url:"conditions"`
	// This id and ts were already stored; nothing changed.
	Duplicate bool   `json:"duplicate" url:"duplicate"`
	ID        string `json:"id" url:"id"`
	Received  int64  `json:"received" url:"received"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DevicePosted) GetConditions() []*DeviceCondition {
	if d == nil {
		return nil
	}
	return d.Conditions
}

func (d *DevicePosted) GetDuplicate() bool {
	if d == nil {
		return false
	}
	return d.Duplicate
}

func (d *DevicePosted) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DevicePosted) GetReceived() int64 {
	if d == nil {
		return 0
	}
	return d.Received
}

func (d *DevicePosted) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DevicePosted) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetConditions sets the Conditions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePosted) SetConditions(conditions []*DeviceCondition) {
	d.Conditions = conditions
	d.require(devicePostedFieldConditions)
}

// SetDuplicate sets the Duplicate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePosted) SetDuplicate(duplicate bool) {
	d.Duplicate = duplicate
	d.require(devicePostedFieldDuplicate)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePosted) SetID(id string) {
	d.ID = id
	d.require(devicePostedFieldID)
}

// SetReceived sets the Received field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePosted) SetReceived(received int64) {
	d.Received = received
	d.require(devicePostedFieldReceived)
}

func (d *DevicePosted) UnmarshalJSON(data []byte) error {
	type unmarshaler DevicePosted
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DevicePosted(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicePosted) MarshalJSON() ([]byte, error) {
	type embed DevicePosted
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DevicePosted) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	devicePowerFieldSource = big.NewInt(1 << 0)
	devicePowerFieldStatus = big.NewInt(1 << 1)
	devicePowerFieldWhy    = big.NewInt(1 << 2)
)

type DevicePower struct {
	Source *DevicePowerSource `json:"source,omitempty" url:"source,omitempty"`
	Status DevicePowerStatus  `json:"status" url:"status"`
	Why    *string            `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DevicePower) GetSource() *DevicePowerSource {
	if d == nil {
		return nil
	}
	return d.Source
}

func (d *DevicePower) GetStatus() DevicePowerStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DevicePower) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DevicePower) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DevicePower) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePower) SetSource(source *DevicePowerSource) {
	d.Source = source
	d.require(devicePowerFieldSource)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePower) SetStatus(status DevicePowerStatus) {
	d.Status = status
	d.require(devicePowerFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DevicePower) SetWhy(why *string) {
	d.Why = why
	d.require(devicePowerFieldWhy)
}

func (d *DevicePower) UnmarshalJSON(data []byte) error {
	type embed DevicePower
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DevicePower(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DevicePower) MarshalJSON() ([]byte, error) {
	type embed DevicePower
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DevicePower) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DevicePowerSource string

const (
	DevicePowerSourceAc      DevicePowerSource = "ac"
	DevicePowerSourceBattery DevicePowerSource = "battery"
	DevicePowerSourceUps     DevicePowerSource = "ups"
)

func NewDevicePowerSourceFromString(s string) (DevicePowerSource, error) {
	switch s {
	case "ac":
		return DevicePowerSourceAc, nil
	case "battery":
		return DevicePowerSourceBattery, nil
	case "ups":
		return DevicePowerSourceUps, nil
	}
	var t DevicePowerSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DevicePowerSource) Ptr() *DevicePowerSource {
	return &d
}

type DevicePowerStatus string

const (
	DevicePowerStatusOk      DevicePowerStatus = "ok"
	DevicePowerStatusUnknown DevicePowerStatus = "unknown"
)

func NewDevicePowerStatusFromString(s string) (DevicePowerStatus, error) {
	switch s {
	case "ok":
		return DevicePowerStatusOk, nil
	case "unknown":
		return DevicePowerStatusUnknown, nil
	}
	var t DevicePowerStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DevicePowerStatus) Ptr() *DevicePowerStatus {
	return &d
}

var (
	deviceReportFieldBattery = big.NewInt(1 << 0)
	deviceReportFieldClaims  = big.NewInt(1 << 1)
	deviceReportFieldCPU     = big.NewInt(1 << 2)
	deviceReportFieldDisks   = big.NewInt(1 << 3)
	deviceReportFieldHost    = big.NewInt(1 << 4)
	deviceReportFieldID      = big.NewInt(1 << 5)
	deviceReportFieldKeeper  = big.NewInt(1 << 6)
	deviceReportFieldLid     = big.NewInt(1 << 7)
	deviceReportFieldMemory  = big.NewInt(1 << 8)
	deviceReportFieldNextS   = big.NewInt(1 << 9)
	deviceReportFieldPower   = big.NewInt(1 << 10)
	deviceReportFieldReason  = big.NewInt(1 << 11)
	deviceReportFieldRig     = big.NewInt(1 << 12)
	deviceReportFieldSchema  = big.NewInt(1 << 13)
	deviceReportFieldSleep   = big.NewInt(1 << 14)
	deviceReportFieldTool    = big.NewInt(1 << 15)
	deviceReportFieldTs      = big.NewInt(1 << 16)
)

type DeviceReport struct {
	Battery *DeviceBattery `json:"battery" url:"battery"`
	// Who holds the machine now; absent when the reporting tool does not know.
	Claims *DeviceClaims `json:"claims,omitempty" url:"claims,omitempty"`
	CPU    *DeviceCPU    `json:"cpu" url:"cpu"`
	// The system volume and the volume the tool keeps its data on; one entry with both roles when they are the same volume.
	Disks []*DeviceDisk `json:"disks" url:"disks"`
	Host  *DeviceHost   `json:"host" url:"host"`
	// The machine id: 16 random hex digits made once per machine. Derived from nothing about the machine.
	ID     string        `json:"id" url:"id"`
	Keeper *DeviceKeeper `json:"keeper" url:"keeper"`
	Lid    *DeviceLid    `json:"lid" url:"lid"`
	Memory *DeviceMemory `json:"memory" url:"memory"`
	// The device promises its next report within this many seconds; 0 promises none (reason stop or once).
	NextS int64        `json:"next_s" url:"next_s"`
	Power *DevicePower `json:"power" url:"power"`
	// Why it was sent.
	Reason DeviceReportReason `json:"reason" url:"reason"`
	// The Claude worker claude-rig set up; absent when the reporting tool does not know.
	Rig *DeviceRig `json:"rig,omitempty" url:"rig,omitempty"`
	// The report's schema number; 1 today. The Worker refuses one it does not know.
	Schema int          `json:"schema" url:"schema"`
	Sleep  *DeviceSleep `json:"sleep" url:"sleep"`
	Tool   *DeviceTool  `json:"tool" url:"tool"`
	// When the device read this, by its own clock, Unix milliseconds. Lateness is judged by when the Worker received it, never by this.
	Ts int64 `json:"ts" url:"ts"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceReport) GetBattery() *DeviceBattery {
	if d == nil {
		return nil
	}
	return d.Battery
}

func (d *DeviceReport) GetClaims() *DeviceClaims {
	if d == nil {
		return nil
	}
	return d.Claims
}

func (d *DeviceReport) GetCPU() *DeviceCPU {
	if d == nil {
		return nil
	}
	return d.CPU
}

func (d *DeviceReport) GetDisks() []*DeviceDisk {
	if d == nil {
		return nil
	}
	return d.Disks
}

func (d *DeviceReport) GetHost() *DeviceHost {
	if d == nil {
		return nil
	}
	return d.Host
}

func (d *DeviceReport) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeviceReport) GetKeeper() *DeviceKeeper {
	if d == nil {
		return nil
	}
	return d.Keeper
}

func (d *DeviceReport) GetLid() *DeviceLid {
	if d == nil {
		return nil
	}
	return d.Lid
}

func (d *DeviceReport) GetMemory() *DeviceMemory {
	if d == nil {
		return nil
	}
	return d.Memory
}

func (d *DeviceReport) GetNextS() int64 {
	if d == nil {
		return 0
	}
	return d.NextS
}

func (d *DeviceReport) GetPower() *DevicePower {
	if d == nil {
		return nil
	}
	return d.Power
}

func (d *DeviceReport) GetReason() DeviceReportReason {
	if d == nil {
		return ""
	}
	return d.Reason
}

func (d *DeviceReport) GetRig() *DeviceRig {
	if d == nil {
		return nil
	}
	return d.Rig
}

func (d *DeviceReport) GetSchema() int {
	if d == nil {
		return 0
	}
	return d.Schema
}

func (d *DeviceReport) GetSleep() *DeviceSleep {
	if d == nil {
		return nil
	}
	return d.Sleep
}

func (d *DeviceReport) GetTool() *DeviceTool {
	if d == nil {
		return nil
	}
	return d.Tool
}

func (d *DeviceReport) GetTs() int64 {
	if d == nil {
		return 0
	}
	return d.Ts
}

func (d *DeviceReport) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceReport) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetBattery sets the Battery field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetBattery(battery *DeviceBattery) {
	d.Battery = battery
	d.require(deviceReportFieldBattery)
}

// SetClaims sets the Claims field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetClaims(claims *DeviceClaims) {
	d.Claims = claims
	d.require(deviceReportFieldClaims)
}

// SetCPU sets the CPU field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetCPU(cpu *DeviceCPU) {
	d.CPU = cpu
	d.require(deviceReportFieldCPU)
}

// SetDisks sets the Disks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetDisks(disks []*DeviceDisk) {
	d.Disks = disks
	d.require(deviceReportFieldDisks)
}

// SetHost sets the Host field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetHost(host *DeviceHost) {
	d.Host = host
	d.require(deviceReportFieldHost)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetID(id string) {
	d.ID = id
	d.require(deviceReportFieldID)
}

// SetKeeper sets the Keeper field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetKeeper(keeper *DeviceKeeper) {
	d.Keeper = keeper
	d.require(deviceReportFieldKeeper)
}

// SetLid sets the Lid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetLid(lid *DeviceLid) {
	d.Lid = lid
	d.require(deviceReportFieldLid)
}

// SetMemory sets the Memory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetMemory(memory *DeviceMemory) {
	d.Memory = memory
	d.require(deviceReportFieldMemory)
}

// SetNextS sets the NextS field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetNextS(nextS int64) {
	d.NextS = nextS
	d.require(deviceReportFieldNextS)
}

// SetPower sets the Power field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetPower(power *DevicePower) {
	d.Power = power
	d.require(deviceReportFieldPower)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetReason(reason DeviceReportReason) {
	d.Reason = reason
	d.require(deviceReportFieldReason)
}

// SetRig sets the Rig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetRig(rig *DeviceRig) {
	d.Rig = rig
	d.require(deviceReportFieldRig)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetSchema(schema int) {
	d.Schema = schema
	d.require(deviceReportFieldSchema)
}

// SetSleep sets the Sleep field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetSleep(sleep *DeviceSleep) {
	d.Sleep = sleep
	d.require(deviceReportFieldSleep)
}

// SetTool sets the Tool field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetTool(tool *DeviceTool) {
	d.Tool = tool
	d.require(deviceReportFieldTool)
}

// SetTs sets the Ts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceReport) SetTs(ts int64) {
	d.Ts = ts
	d.require(deviceReportFieldTs)
}

func (d *DeviceReport) UnmarshalJSON(data []byte) error {
	type embed DeviceReport
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceReport(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceReport) MarshalJSON() ([]byte, error) {
	type embed DeviceReport
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceReport) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Why it was sent.
type DeviceReportReason string

const (
	DeviceReportReasonStart    DeviceReportReason = "start"
	DeviceReportReasonChange   DeviceReportReason = "change"
	DeviceReportReasonInterval DeviceReportReason = "interval"
	DeviceReportReasonStop     DeviceReportReason = "stop"
	DeviceReportReasonOnce     DeviceReportReason = "once"
)

func NewDeviceReportReasonFromString(s string) (DeviceReportReason, error) {
	switch s {
	case "start":
		return DeviceReportReasonStart, nil
	case "change":
		return DeviceReportReasonChange, nil
	case "interval":
		return DeviceReportReasonInterval, nil
	case "stop":
		return DeviceReportReasonStop, nil
	case "once":
		return DeviceReportReasonOnce, nil
	}
	var t DeviceReportReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceReportReason) Ptr() *DeviceReportReason {
	return &d
}

var (
	deviceRigFieldClaudeVersion  = big.NewInt(1 << 0)
	deviceRigFieldCommit         = big.NewInt(1 << 1)
	deviceRigFieldConfigApplied  = big.NewInt(1 << 2)
	deviceRigFieldLoggedIn       = big.NewInt(1 << 3)
	deviceRigFieldSessionRunning = big.NewInt(1 << 4)
	deviceRigFieldStatus         = big.NewInt(1 << 5)
	deviceRigFieldToolsInstalled = big.NewInt(1 << 6)
	deviceRigFieldWhy            = big.NewInt(1 << 7)
	deviceRigFieldWorkDir        = big.NewInt(1 << 8)
)

type DeviceRig struct {
	// What claude --version prints; absent when Claude is not installed.
	ClaudeVersion *string `json:"claude_version,omitempty" url:"claude_version,omitempty"`
	// The claude-rig commit it last ran; absent when not known.
	Commit *string `json:"commit,omitempty" url:"commit,omitempty"`
	// The rig's Claude configuration is applied.
	ConfigApplied *bool `json:"config_applied,omitempty" url:"config_applied,omitempty"`
	// Claude is logged in.
	LoggedIn *bool `json:"logged_in,omitempty" url:"logged_in,omitempty"`
	// A Claude session is running for the rig.
	SessionRunning *bool `json:"session_running,omitempty" url:"session_running,omitempty"`
	// none: claude-rig never set this machine up.
	Status DeviceRigStatus `json:"status" url:"status"`
	// Every tool the rig installs is there.
	ToolsInstalled *bool   `json:"tools_installed,omitempty" url:"tools_installed,omitempty"`
	Why            *string `json:"why,omitempty" url:"why,omitempty"`
	// Where its jobs run, the home directory written as ~.
	WorkDir *string `json:"work_dir,omitempty" url:"work_dir,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceRig) GetClaudeVersion() *string {
	if d == nil {
		return nil
	}
	return d.ClaudeVersion
}

func (d *DeviceRig) GetCommit() *string {
	if d == nil {
		return nil
	}
	return d.Commit
}

func (d *DeviceRig) GetConfigApplied() *bool {
	if d == nil {
		return nil
	}
	return d.ConfigApplied
}

func (d *DeviceRig) GetLoggedIn() *bool {
	if d == nil {
		return nil
	}
	return d.LoggedIn
}

func (d *DeviceRig) GetSessionRunning() *bool {
	if d == nil {
		return nil
	}
	return d.SessionRunning
}

func (d *DeviceRig) GetStatus() DeviceRigStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceRig) GetToolsInstalled() *bool {
	if d == nil {
		return nil
	}
	return d.ToolsInstalled
}

func (d *DeviceRig) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceRig) GetWorkDir() *string {
	if d == nil {
		return nil
	}
	return d.WorkDir
}

func (d *DeviceRig) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceRig) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetClaudeVersion sets the ClaudeVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetClaudeVersion(claudeVersion *string) {
	d.ClaudeVersion = claudeVersion
	d.require(deviceRigFieldClaudeVersion)
}

// SetCommit sets the Commit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetCommit(commit *string) {
	d.Commit = commit
	d.require(deviceRigFieldCommit)
}

// SetConfigApplied sets the ConfigApplied field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetConfigApplied(configApplied *bool) {
	d.ConfigApplied = configApplied
	d.require(deviceRigFieldConfigApplied)
}

// SetLoggedIn sets the LoggedIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetLoggedIn(loggedIn *bool) {
	d.LoggedIn = loggedIn
	d.require(deviceRigFieldLoggedIn)
}

// SetSessionRunning sets the SessionRunning field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetSessionRunning(sessionRunning *bool) {
	d.SessionRunning = sessionRunning
	d.require(deviceRigFieldSessionRunning)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetStatus(status DeviceRigStatus) {
	d.Status = status
	d.require(deviceRigFieldStatus)
}

// SetToolsInstalled sets the ToolsInstalled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetToolsInstalled(toolsInstalled *bool) {
	d.ToolsInstalled = toolsInstalled
	d.require(deviceRigFieldToolsInstalled)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetWhy(why *string) {
	d.Why = why
	d.require(deviceRigFieldWhy)
}

// SetWorkDir sets the WorkDir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceRig) SetWorkDir(workDir *string) {
	d.WorkDir = workDir
	d.require(deviceRigFieldWorkDir)
}

func (d *DeviceRig) UnmarshalJSON(data []byte) error {
	type embed DeviceRig
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceRig(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceRig) MarshalJSON() ([]byte, error) {
	type embed DeviceRig
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceRig) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// none: claude-rig never set this machine up.
type DeviceRigStatus string

const (
	DeviceRigStatusOk      DeviceRigStatus = "ok"
	DeviceRigStatusNone    DeviceRigStatus = "none"
	DeviceRigStatusUnknown DeviceRigStatus = "unknown"
)

func NewDeviceRigStatusFromString(s string) (DeviceRigStatus, error) {
	switch s {
	case "ok":
		return DeviceRigStatusOk, nil
	case "none":
		return DeviceRigStatusNone, nil
	case "unknown":
		return DeviceRigStatusUnknown, nil
	}
	var t DeviceRigStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceRigStatus) Ptr() *DeviceRigStatus {
	return &d
}

var (
	deviceSleepFieldDisplayS   = big.NewInt(1 << 0)
	deviceSleepFieldIdleS      = big.NewInt(1 << 1)
	deviceSleepFieldInhibited  = big.NewInt(1 << 2)
	deviceSleepFieldInhibitors = big.NewInt(1 << 3)
	deviceSleepFieldLidAction  = big.NewInt(1 << 4)
	deviceSleepFieldStatus     = big.NewInt(1 << 5)
	deviceSleepFieldWhy        = big.NewInt(1 << 6)
)

type DeviceSleep struct {
	// Idle seconds before the display turns off; 0 is never.
	DisplayS *int64 `json:"display_s,omitempty" url:"display_s,omitempty"`
	// Idle seconds before it sleeps on the current power source; 0 is never.
	IdleS *int64 `json:"idle_s,omitempty" url:"idle_s,omitempty"`
	// Something is holding idle sleep off right now.
	Inhibited *bool `json:"inhibited,omitempty" url:"inhibited,omitempty"`
	// The programs holding it off, by process name only.
	Inhibitors []string `json:"inhibitors,omitempty" url:"inhibitors,omitempty"`
	// What closing the lid does now. nothing is a machine that keeps running closed.
	LidAction *DeviceSleepLidAction `json:"lid_action,omitempty" url:"lid_action,omitempty"`
	// none: a machine that cannot sleep (a container, a CI runner).
	Status DeviceSleepStatus `json:"status" url:"status"`
	Why    *string           `json:"why,omitempty" url:"why,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceSleep) GetDisplayS() *int64 {
	if d == nil {
		return nil
	}
	return d.DisplayS
}

func (d *DeviceSleep) GetIdleS() *int64 {
	if d == nil {
		return nil
	}
	return d.IdleS
}

func (d *DeviceSleep) GetInhibited() *bool {
	if d == nil {
		return nil
	}
	return d.Inhibited
}

func (d *DeviceSleep) GetInhibitors() []string {
	if d == nil {
		return nil
	}
	return d.Inhibitors
}

func (d *DeviceSleep) GetLidAction() *DeviceSleepLidAction {
	if d == nil {
		return nil
	}
	return d.LidAction
}

func (d *DeviceSleep) GetStatus() DeviceSleepStatus {
	if d == nil {
		return ""
	}
	return d.Status
}

func (d *DeviceSleep) GetWhy() *string {
	if d == nil {
		return nil
	}
	return d.Why
}

func (d *DeviceSleep) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceSleep) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetDisplayS sets the DisplayS field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetDisplayS(displayS *int64) {
	d.DisplayS = displayS
	d.require(deviceSleepFieldDisplayS)
}

// SetIdleS sets the IdleS field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetIdleS(idleS *int64) {
	d.IdleS = idleS
	d.require(deviceSleepFieldIdleS)
}

// SetInhibited sets the Inhibited field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetInhibited(inhibited *bool) {
	d.Inhibited = inhibited
	d.require(deviceSleepFieldInhibited)
}

// SetInhibitors sets the Inhibitors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetInhibitors(inhibitors []string) {
	d.Inhibitors = inhibitors
	d.require(deviceSleepFieldInhibitors)
}

// SetLidAction sets the LidAction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetLidAction(lidAction *DeviceSleepLidAction) {
	d.LidAction = lidAction
	d.require(deviceSleepFieldLidAction)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetStatus(status DeviceSleepStatus) {
	d.Status = status
	d.require(deviceSleepFieldStatus)
}

// SetWhy sets the Why field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceSleep) SetWhy(why *string) {
	d.Why = why
	d.require(deviceSleepFieldWhy)
}

func (d *DeviceSleep) UnmarshalJSON(data []byte) error {
	type embed DeviceSleep
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceSleep(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceSleep) MarshalJSON() ([]byte, error) {
	type embed DeviceSleep
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceSleep) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// What closing the lid does now. nothing is a machine that keeps running closed.
type DeviceSleepLidAction string

const (
	DeviceSleepLidActionSleep     DeviceSleepLidAction = "sleep"
	DeviceSleepLidActionHibernate DeviceSleepLidAction = "hibernate"
	DeviceSleepLidActionShutdown  DeviceSleepLidAction = "shutdown"
	DeviceSleepLidActionLock      DeviceSleepLidAction = "lock"
	DeviceSleepLidActionNothing   DeviceSleepLidAction = "nothing"
)

func NewDeviceSleepLidActionFromString(s string) (DeviceSleepLidAction, error) {
	switch s {
	case "sleep":
		return DeviceSleepLidActionSleep, nil
	case "hibernate":
		return DeviceSleepLidActionHibernate, nil
	case "shutdown":
		return DeviceSleepLidActionShutdown, nil
	case "lock":
		return DeviceSleepLidActionLock, nil
	case "nothing":
		return DeviceSleepLidActionNothing, nil
	}
	var t DeviceSleepLidAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceSleepLidAction) Ptr() *DeviceSleepLidAction {
	return &d
}

// none: a machine that cannot sleep (a container, a CI runner).
type DeviceSleepStatus string

const (
	DeviceSleepStatusOk      DeviceSleepStatus = "ok"
	DeviceSleepStatusNone    DeviceSleepStatus = "none"
	DeviceSleepStatusUnknown DeviceSleepStatus = "unknown"
)

func NewDeviceSleepStatusFromString(s string) (DeviceSleepStatus, error) {
	switch s {
	case "ok":
		return DeviceSleepStatusOk, nil
	case "none":
		return DeviceSleepStatusNone, nil
	case "unknown":
		return DeviceSleepStatusUnknown, nil
	}
	var t DeviceSleepStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DeviceSleepStatus) Ptr() *DeviceSleepStatus {
	return &d
}

var (
	deviceStoredFieldReceived = big.NewInt(1 << 0)
	deviceStoredFieldReport   = big.NewInt(1 << 1)
)

type DeviceStored struct {
	Received int64         `json:"received" url:"received"`
	Report   *DeviceReport `json:"report" url:"report"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceStored) GetReceived() int64 {
	if d == nil {
		return 0
	}
	return d.Received
}

func (d *DeviceStored) GetReport() *DeviceReport {
	if d == nil {
		return nil
	}
	return d.Report
}

func (d *DeviceStored) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceStored) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetReceived sets the Received field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceStored) SetReceived(received int64) {
	d.Received = received
	d.require(deviceStoredFieldReceived)
}

// SetReport sets the Report field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceStored) SetReport(report *DeviceReport) {
	d.Report = report
	d.require(deviceStoredFieldReport)
}

func (d *DeviceStored) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceStored
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceStored(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceStored) MarshalJSON() ([]byte, error) {
	type embed DeviceStored
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceStored) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceToolFieldCommand = big.NewInt(1 << 0)
	deviceToolFieldName    = big.NewInt(1 << 1)
	deviceToolFieldVersion = big.NewInt(1 << 2)
)

type DeviceTool struct {
	// The command that read it: doctor, device, device-watch, awake.
	Command string `json:"command" url:"command"`
	// The program: claude-rig, irgo-winvm.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Its version, or the commit it runs.
	Version string `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (d *DeviceTool) GetCommand() string {
	if d == nil {
		return ""
	}
	return d.Command
}

func (d *DeviceTool) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DeviceTool) GetVersion() string {
	if d == nil {
		return ""
	}
	return d.Version
}

func (d *DeviceTool) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.ExtraProperties
}

func (d *DeviceTool) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetCommand sets the Command field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceTool) SetCommand(command string) {
	d.Command = command
	d.require(deviceToolFieldCommand)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceTool) SetName(name *string) {
	d.Name = name
	d.require(deviceToolFieldName)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceTool) SetVersion(version string) {
	d.Version = version
	d.require(deviceToolFieldVersion)
}

func (d *DeviceTool) UnmarshalJSON(data []byte) error {
	type embed DeviceTool
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DeviceTool(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.ExtraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceTool) MarshalJSON() ([]byte, error) {
	type embed DeviceTool
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, d.ExtraProperties)
}

func (d *DeviceTool) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceViewFieldConditions = big.NewInt(1 << 0)
	deviceViewFieldDue        = big.NewInt(1 << 1)
	deviceViewFieldReceived   = big.NewInt(1 << 2)
	deviceViewFieldReport     = big.NewInt(1 << 3)
)

type DeviceView struct {
	// Empty when there is nothing to say.
	Conditions []*DeviceCondition `json:"conditions" url:"conditions"`
	// When the next was promised by: received + next_s. Absent when none was.
	Due *int64 `json:"due,omitempty" url:"due,omitempty"`
	// When the Worker received it, Unix milliseconds.
	Received int64 `json:"received" url:"received"`
	// The newest report, as posted.
	Report *DeviceReport `json:"report" url:"report"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceView) GetConditions() []*DeviceCondition {
	if d == nil {
		return nil
	}
	return d.Conditions
}

func (d *DeviceView) GetDue() *int64 {
	if d == nil {
		return nil
	}
	return d.Due
}

func (d *DeviceView) GetReceived() int64 {
	if d == nil {
		return 0
	}
	return d.Received
}

func (d *DeviceView) GetReport() *DeviceReport {
	if d == nil {
		return nil
	}
	return d.Report
}

func (d *DeviceView) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceView) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetConditions sets the Conditions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceView) SetConditions(conditions []*DeviceCondition) {
	d.Conditions = conditions
	d.require(deviceViewFieldConditions)
}

// SetDue sets the Due field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceView) SetDue(due *int64) {
	d.Due = due
	d.require(deviceViewFieldDue)
}

// SetReceived sets the Received field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceView) SetReceived(received int64) {
	d.Received = received
	d.require(deviceViewFieldReceived)
}

// SetReport sets the Report field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceView) SetReport(report *DeviceReport) {
	d.Report = report
	d.require(deviceViewFieldReport)
}

func (d *DeviceView) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceView
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceView(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceView) MarshalJSON() ([]byte, error) {
	type embed DeviceView
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceView) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
