// Code generated by Fern. DO NOT EDIT.

package fleet

// Environment defines the environment with multiple base URLs.
type Environment struct {
	Base       string
	Production string
}

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Default Environment
}{
	Default: Environment{
		Base:       "https://fleet-api.gedw99.workers.dev",
		Production: "wss://fleet-api.gedw99.workers.dev",
	},
}
