// Code generated by Fern. DO NOT EDIT.

package fleet

import (
	json "encoding/json"
	core "github.com/joeblew999/fleet-api/sdk/go/core"
)

// Request Entity Too Large
type ContentTooLargeError struct {
	*core.APIError
	Body *ErrorModel
}

func (c *ContentTooLargeError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 413
	c.Body = body
	return nil
}

func (c *ContentTooLargeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ContentTooLargeError) Unwrap() error {
	return c.APIError
}

func (c *ContentTooLargeError) GetBody() *ErrorModel {
	if c == nil {
		return nil
	}
	return c.Body
}

// Internal Server Error
type InternalServerError struct {
	*core.APIError
	Body *ErrorModel
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

func (i *InternalServerError) GetBody() *ErrorModel {
	if i == nil {
		return nil
	}
	return i.Body
}

// Not Found
type NotFoundError struct {
	*core.APIError
	Body *ErrorModel
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

func (n *NotFoundError) GetBody() *ErrorModel {
	if n == nil {
		return nil
	}
	return n.Body
}

// Unauthorized
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorModel
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

func (u *UnauthorizedError) GetBody() *ErrorModel {
	if u == nil {
		return nil
	}
	return u.Body
}

// Unprocessable Entity
type UnprocessableEntityError struct {
	*core.APIError
	Body *ErrorModel
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}

func (u *UnprocessableEntityError) GetBody() *ErrorModel {
	if u == nil {
		return nil
	}
	return u.Body
}
