// Code generated by Fern. DO NOT EDIT.

package fleet

import (
	core "github.com/joeblew999/fleet-api/sdk/go/core"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &ForbiddenError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &InternalServerError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	422: func(apiError *core.APIError) error {
		return &UnprocessableEntityError{
			APIError: apiError,
		}
	},
	413: func(apiError *core.APIError) error {
		return &ContentTooLargeError{
			APIError: apiError,
		}
	},
}
