// Code generated by Fern. DO NOT EDIT.

package fleet

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
	big "math/big"
)

var (
	helloOutputBodyFieldMessage = big.NewInt(1 << 0)
)

type HelloOutputBody struct {
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HelloOutputBody) GetMessage() string {
	if h == nil {
		return ""
	}
	return h.Message
}

func (h *HelloOutputBody) GetExtraProperties() map[string]interface{} {
	if h == nil {
		return nil
	}
	return h.extraProperties
}

func (h *HelloOutputBody) require(field *big.Int) {
	next := new(big.Int)
	if h.explicitFields != nil {
		next.Set(h.explicitFields)
	}
	next.Or(next, field)
	h.explicitFields = next
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HelloOutputBody) SetMessage(message string) {
	h.Message = message
	h.require(helloOutputBodyFieldMessage)
}

func (h *HelloOutputBody) UnmarshalJSON(data []byte) error {
	type unmarshaler HelloOutputBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HelloOutputBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HelloOutputBody) MarshalJSON() ([]byte, error) {
	type embed HelloOutputBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HelloOutputBody) String() string {
	if h == nil {
		return "<nil>"
	}
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}
