// Code generated by Fern. DO NOT EDIT.

package fleet

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
	big "math/big"
)

var (
	errorDetailFieldLocation = big.NewInt(1 << 0)
	errorDetailFieldMessage  = big.NewInt(1 << 1)
	errorDetailFieldValue    = big.NewInt(1 << 2)
)

type ErrorDetail struct {
	// Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty" url:"location,omitempty"`
	// Error message text
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// The value at the given location
	Value any `json:"value,omitempty" url:"value,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorDetail) GetLocation() *string {
	if e == nil {
		return nil
	}
	return e.Location
}

func (e *ErrorDetail) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *ErrorDetail) GetValue() any {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *ErrorDetail) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorDetail) require(field *big.Int) {
	next := new(big.Int)
	if e.explicitFields != nil {
		next.Set(e.explicitFields)
	}
	next.Or(next, field)
	e.explicitFields = next
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorDetail) SetLocation(location *string) {
	e.Location = location
	e.require(errorDetailFieldLocation)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorDetail) SetMessage(message *string) {
	e.Message = message
	e.require(errorDetailFieldMessage)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorDetail) SetValue(value any) {
	e.Value = value
	e.require(errorDetailFieldValue)
}

func (e *ErrorDetail) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorDetail
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorDetail(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorDetail) MarshalJSON() ([]byte, error) {
	type embed ErrorDetail
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorDetail) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	errorModelFieldDetail   = big.NewInt(1 << 0)
	errorModelFieldErrors   = big.NewInt(1 << 1)
	errorModelFieldInstance = big.NewInt(1 << 2)
	errorModelFieldStatus   = big.NewInt(1 << 3)
	errorModelFieldTitle    = big.NewInt(1 << 4)
	errorModelFieldType     = big.NewInt(1 << 5)
)

type ErrorModel struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty" url:"detail,omitempty"`
	// Optional list of individual error details
	Errors []*ErrorDetail `json:"errors,omitempty" url:"errors,omitempty"`
	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty" url:"instance,omitempty"`
	// HTTP status code
	Status *int64 `json:"status,omitempty" url:"status,omitempty"`
	// A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty" url:"title,omitempty"`
	// A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorModel) GetDetail() *string {
	if e == nil {
		return nil
	}
	return e.Detail
}

func (e *ErrorModel) GetErrors() []*ErrorDetail {
	if e == nil {
		return nil
	}
	return e.Errors
}

func (e *ErrorModel) GetInstance() *string {
	if e == nil {
		return nil
	}
	return e.Instance
}

func (e *ErrorModel) GetStatus() *int64 {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *ErrorModel) GetTitle() *string {
	if e == nil {
		return nil
	}
	return e.Title
}

func (e *ErrorModel) GetType() *string {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *ErrorModel) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorModel) require(field *big.Int) {
	next := new(big.Int)
	if e.explicitFields != nil {
		next.Set(e.explicitFields)
	}
	next.Or(next, field)
	e.explicitFields = next
}

// SetDetail sets the Detail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetDetail(detail *string) {
	e.Detail = detail
	e.require(errorModelFieldDetail)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetErrors(errors []*ErrorDetail) {
	e.Errors = errors
	e.require(errorModelFieldErrors)
}

// SetInstance sets the Instance field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetInstance(instance *string) {
	e.Instance = instance
	e.require(errorModelFieldInstance)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetStatus(status *int64) {
	e.Status = status
	e.require(errorModelFieldStatus)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetTitle(title *string) {
	e.Title = title
	e.require(errorModelFieldTitle)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorModel) SetType(type_ *string) {
	e.Type = type_
	e.require(errorModelFieldType)
}

func (e *ErrorModel) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorModel
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorModel(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorModel) MarshalJSON() ([]byte, error) {
	type embed ErrorModel
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorModel) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}
