CREATE TABLE IF NOT EXISTS devices (id TEXT PRIMARY KEY, ts INTEGER NOT NULL, received INTEGER NOT NULL, due INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL, next_s INTEGER NOT NULL, name TEXT NOT NULL, os TEXT NOT NULL, report TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS device_reports (id TEXT NOT NULL, ts INTEGER NOT NULL, received INTEGER NOT NULL, report TEXT NOT NULL, PRIMARY KEY (id, ts));
CREATE INDEX IF NOT EXISTS device_reports_received ON device_reports (received);
