// Code generated by Fern. DO NOT EDIT.

package core

import (
	fmt "fmt"
	http "net/http"
	url "net/url"
	strings "strings"
)

// RequestOption adapts the behavior of the client or an individual request.
type RequestOption interface {
	applyRequestOptions(*RequestOptions)
}

// RequestOptions defines all of the possible request options.
//
// This type is primarily used by the generated code and is not meant
// to be used directly; use the option package instead.
type RequestOptions struct {
	BaseURL                    string
	Environment                interface{}
	HTTPClient                 HTTPClient
	HTTPHeader                 http.Header
	BodyProperties             map[string]interface{}
	QueryParameters            url.Values
	MaxAttempts                uint
	MaxBufSize                 int
	MaxStreamReconnectAttempts uint
	DisableStreamReconnection  bool
	DisableRetries             bool
	AccessClientID             string
	AccessClientSecret         string
	AccessToken                string
	AccessTokenFunc            func() (string, error)
	Token                      string
	TokenFunc                  func() (string, error)
}

// NewRequestOptions returns a new *RequestOptions value.
//
// This function is primarily used by the generated code and is not meant
// to be used directly; use RequestOption instead.
func NewRequestOptions(opts ...RequestOption) *RequestOptions {
	options := &RequestOptions{
		HTTPHeader:      make(http.Header),
		BodyProperties:  make(map[string]interface{}),
		QueryParameters: make(url.Values),
	}
	for _, opt := range opts {
		opt.applyRequestOptions(options)
	}
	return options
}

// ToHeader maps the configured request options into a http.Header used
// for the request(s).
func (r *RequestOptions) ToHeader() http.Header {
	header := r.cloneHeader()
	return header
}

// AuthHeadersForEndpoint returns the auth headers to apply for an endpoint,
// given the endpoint's static security requirements. It routes to the first
// requirement whose schemes all have credentials available (OR across the
// list, AND within a requirement).
func (r *RequestOptions) AuthHeadersForEndpoint(security [][]string) (http.Header, error) {
	if len(security) == 0 {
		return make(http.Header), nil
	}
	availableAuthHeaders := make(map[string]http.Header)
	token := r.Token
	if token == "" && r.TokenFunc != nil {
		if value, err := r.TokenFunc(); err == nil {
			token = value
		}
	}
	if token != "" {
		tokenHeaders := make(http.Header)
		tokenHeaders.Set("Authorization", "Bearer "+token)
		availableAuthHeaders["oidc"] = tokenHeaders
		availableAuthHeaders["bearer"] = tokenHeaders
	}
	if r.AccessClientID != "" {
		headerValues := make(http.Header)
		headerValues.Set("CF-Access-Client-Id", fmt.Sprintf("%v", r.AccessClientID))
		availableAuthHeaders["accessClientId"] = headerValues
	}
	if r.AccessClientSecret != "" {
		headerValues := make(http.Header)
		headerValues.Set("CF-Access-Client-Secret", fmt.Sprintf("%v", r.AccessClientSecret))
		availableAuthHeaders["accessClientSecret"] = headerValues
	}
	for _, requirement := range security {
		satisfied := true
		for _, schemeKey := range requirement {
			if _, ok := availableAuthHeaders[schemeKey]; !ok {
				satisfied = false
				break
			}
		}
		if !satisfied {
			continue
		}
		combined := make(http.Header)
		for _, schemeKey := range requirement {
			for name, values := range availableAuthHeaders[schemeKey] {
				for _, value := range values {
					combined.Set(name, value)
				}
			}
		}
		return combined, nil
	}
	missing := make([]string, 0, len(security))
	for _, requirement := range security {
		var missingSchemes []string
		for _, schemeKey := range requirement {
			if _, ok := availableAuthHeaders[schemeKey]; !ok {
				missingSchemes = append(missingSchemes, schemeKey)
			}
		}
		missing = append(missing, strings.Join(missingSchemes, " AND "))
	}
	return nil, fmt.Errorf(
		"no authentication credentials provided that satisfy the endpoint's security requirements; please provide credentials for: %s",
		strings.Join(missing, " OR "),
	)
}

func (r *RequestOptions) cloneHeader() http.Header {
	return r.HTTPHeader.Clone()
}

// BaseURLOption implements the RequestOption interface.
type BaseURLOption struct {
	BaseURL string
}

func (b *BaseURLOption) applyRequestOptions(opts *RequestOptions) {
	opts.BaseURL = b.BaseURL
}

// HTTPClientOption implements the RequestOption interface.
type HTTPClientOption struct {
	HTTPClient HTTPClient
}

func (h *HTTPClientOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPClient = h.HTTPClient
}

// HTTPHeaderOption implements the RequestOption interface.
type HTTPHeaderOption struct {
	HTTPHeader http.Header
}

func (h *HTTPHeaderOption) applyRequestOptions(opts *RequestOptions) {
	opts.HTTPHeader = h.HTTPHeader
}

// BodyPropertiesOption implements the RequestOption interface.
type BodyPropertiesOption struct {
	BodyProperties map[string]interface{}
}

func (b *BodyPropertiesOption) applyRequestOptions(opts *RequestOptions) {
	opts.BodyProperties = b.BodyProperties
}

// QueryParametersOption implements the RequestOption interface.
type QueryParametersOption struct {
	QueryParameters url.Values
}

func (q *QueryParametersOption) applyRequestOptions(opts *RequestOptions) {
	opts.QueryParameters = q.QueryParameters
}

// MaxAttemptsOption implements the RequestOption interface.
type MaxAttemptsOption struct {
	MaxAttempts uint
}

func (m *MaxAttemptsOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxAttempts = m.MaxAttempts
}

// MaxBufSizeOption implements the RequestOption interface.
type MaxBufSizeOption struct {
	MaxBufSize int
}

func (m *MaxBufSizeOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxBufSize = m.MaxBufSize
}

// MaxStreamReconnectAttemptsOption implements the RequestOption interface.
type MaxStreamReconnectAttemptsOption struct {
	MaxStreamReconnectAttempts uint
}

func (m *MaxStreamReconnectAttemptsOption) applyRequestOptions(opts *RequestOptions) {
	opts.MaxStreamReconnectAttempts = m.MaxStreamReconnectAttempts
}

// WithoutStreamReconnectionOption implements the RequestOption interface.
type WithoutStreamReconnectionOption struct{}

func (w *WithoutStreamReconnectionOption) applyRequestOptions(opts *RequestOptions) {
	opts.DisableStreamReconnection = true
}

// WithoutRetriesOption implements the RequestOption interface.
type WithoutRetriesOption struct{}

func (w *WithoutRetriesOption) applyRequestOptions(opts *RequestOptions) {
	opts.DisableRetries = true
}

// EnvironmentOption implements the RequestOption interface.
type EnvironmentOption struct {
	Environment interface{}
}

func (e *EnvironmentOption) applyRequestOptions(opts *RequestOptions) {
	opts.Environment = e.Environment
}

// AccessClientIDOption implements the RequestOption interface.
type AccessClientIDOption struct {
	AccessClientID string
}

func (a *AccessClientIDOption) applyRequestOptions(opts *RequestOptions) {
	opts.AccessClientID = a.AccessClientID
}

// AccessClientSecretOption implements the RequestOption interface.
type AccessClientSecretOption struct {
	AccessClientSecret string
}

func (a *AccessClientSecretOption) applyRequestOptions(opts *RequestOptions) {
	opts.AccessClientSecret = a.AccessClientSecret
}

// AccessTokenOption implements the RequestOption interface.
type AccessTokenOption struct {
	AccessToken string
}

func (a *AccessTokenOption) applyRequestOptions(opts *RequestOptions) {
	opts.AccessToken = a.AccessToken
}

// AccessTokenFuncOption implements the RequestOption interface.
type AccessTokenFuncOption struct {
	AccessTokenFunc func() (string, error)
}

func (a *AccessTokenFuncOption) applyRequestOptions(opts *RequestOptions) {
	opts.AccessTokenFunc = a.AccessTokenFunc
}

// TokenOption implements the RequestOption interface.
type TokenOption struct {
	Token string
}

func (t *TokenOption) applyRequestOptions(opts *RequestOptions) {
	opts.Token = t.Token
}

// TokenFuncOption implements the RequestOption interface.
type TokenFuncOption struct {
	TokenFunc func() (string, error)
}

func (t *TokenFuncOption) applyRequestOptions(opts *RequestOptions) {
	opts.TokenFunc = t.TokenFunc
}
