// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/joeblew999/fleet-api/sdk/go/core"
	devices "github.com/joeblew999/fleet-api/sdk/go/devices"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
	meta "github.com/joeblew999/fleet-api/sdk/go/meta"
	option "github.com/joeblew999/fleet-api/sdk/go/option"
)

type Client struct {
	Devices *devices.Client
	Meta    *meta.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Devices: devices.NewClient(options),
		Meta:    meta.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
