// Code generated by Fern. DO NOT EDIT.

package meta

import (
	context "context"

	fleet "github.com/joeblew999/fleet-api/sdk/go"
	core "github.com/joeblew999/fleet-api/sdk/go/core"
	internal "github.com/joeblew999/fleet-api/sdk/go/internal"
	option "github.com/joeblew999/fleet-api/sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Meta.Hello(
//	    context.TODO(),
//	)
func (c *Client) Hello(
	ctx context.Context,
	opts ...option.RequestOption,
) (*fleet.HelloOutputBody, error) {
	response, err := c.WithRawResponse.Hello(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
